<!--<link rel="stylesheet"
      href="<?php /*echo Mage::getBaseUrl('skin');*/?>frontend/default/default/bootstrap-3.2.0/bootstrap.min.css">
<link rel="stylesheet"
      href="<?php /*echo Mage::getBaseUrl('skin');*/?>frontend/default/default/bootstrap-3.2.0/bootstrap-theme.min.css">
<script src="<?php /*echo Mage::getBaseUrl('skin');*/?>frontend/default/default/js/jquery-1.11.1.min.js"></script>
<script src="<?php /*echo Mage::getBaseUrl('skin');*/?>frontend/default/default/bootstrap-3.2.0/js/bootstrap.min.js"></script>-->