<?php $posts = $this->getPosts(); ?>
<div class="block block-latestblog span4">
<div class="block-title"><?php echo $this->__('Latest Blog');?></div>
<div class="navigation">
    <span class="next">Next</span>
    <span class="prev">Prev</span>
</div>
<div class="block-content">
    <ul class="list-blog">
    <?php
    $i = 0; $j=0; //echo(count($posts)); die();
    foreach ($posts as $post): ?>
        <?php
        $j++;
        if($j==7) break;
        if($i==0) {?>
        <li class="item">
        <?php
        } ?>
        <div class="item-post<?php echo ($i==3)?' last':'';?> clearfix">
            <div class="date">
                <?php
                $_ct= new Zend_Date($post->getCreatedTime()); ?>
                <span class="d-day"><?php echo $_ct->toString('d');  ?></span>
                <span class="d-month"><?php echo $_ct->toString('MMM'); ?></span>
            </div>
            <?php
            $str = preg_replace ( "/\<img[^\>]*>/", '', $post->getPostContent());
            ?>
            <div class="postTitle">
                <a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a>
            </div>
            <div class="postContent">
                <?php echo Mage::helper('core/string')->truncate($str, 85); ?>
            </div>
        </div>
        <?php
        $i++;
        if( ($i%4==0 && $i!=0)|| $i==count($posts) ){ $i=0;?>
        </li>
        <?php }
    endforeach; ?>
    </ul>
</div>
</div>
<?php
if (null == Mage::registry('sns.jquery')){
    Mage::register('sns.jquery', 1);
    return 'sns/slider/js/jquery-1.7.2.min.js';
}
if (null == Mage::registry('sns.jquerynoconflict')){
    Mage::register('sns.jquerynoconflict', 1);
    return 'sns/slider/js/sns.noconflict.js';
}
if (null == Mage::registry('sns.caroufredsel')){
    Mage::register('sns.caroufredsel', 1); ?>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('assets/plg_caroufredsel/jquery.carouFredSel-6.2.1-packed.js') ?>"></script>
<?php
}
if (null == Mage::registry('sns.mousewheel')){
    Mage::register('sns.mousewheel', 1); ?>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('assets/plg_caroufredsel/jquery.mousewheel.min.js') ?>"></script>
<?php
}
if (null == Mage::registry('sns.touchswipe')){
    Mage::register('sns.touchswipe', 1); ?>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('assets/plg_caroufredsel/jquery.touchSwipe.min.js') ?>"></script>
<?php
}
if (null == Mage::registry('sns.transit')){
    Mage::register('sns.transit', 1); ?>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('assets/plg_caroufredsel/jquery.transit.min.js') ?>"></script>
<?php
} ?>
<script type="text/javascript">
//<![CDATA[
    $sns_jq(window).load(function(){
        $sns_jq('.block-latestblog ul.list-blog').carouFredSel({
            responsive: true,
            width: '100%',
            scroll: {
                items:1,
                duration:500
            },

            items: {
            //  height: '30%',  //  optionally resize item-height
                width  : '370',
                visible: {
                    min: 1,
                    max: 1
                }
            },
            /*mousewheel: true,
            swipe: {
                onMouse: true,
                onTouch: true
            },*/
            prev: '.block-latestblog .prev',
            next: '.block-latestblog .next',
            auto: false
        });
    });
//]]>
</script>