<?php global $var_snstheme;
// Include cpanel
if( 1==1/*$var_snstheme->getParam('showCpanel')*/ ) {
?>
<div id="sns_cpanel" style="direction:ltr">
    <div class="cpanel-head">CPanel</div>
    <div class="cpanel-set">
        <!-- Multi store -->
        <?php
        if($this->getChildHtml('store_switcher')): ?>
        <div class="accordion-group">
            <div class="accordion-heading" id="sns_cpanelaccordionfirst">
                <a href="#sns_citem_3">Multi Store</a>
            </div>
            <div id="sns_citem_3">
                <div class="accordion-inner clearfix">
                    <!-- Styles -->
                    <div class="cp-item">
                        <?php echo $this->getChildHtml('store_switcher'); ?>
                    </div>
                </div>
            </div>
        </div>
        <?php
        endif; ?>
        <!--Body-->
        <div class="accordion-group">
            <div class="accordion-heading">
                <a href="#sns_citem_1">Body</a>
            </div>
            <div id="sns_citem_1">
                <div class="accordion-inner clearfix">
                    <!-- Body font-size -->
                    <div class="cp-item">
                        <span>Font-size</span>
                        <div class="inner">
                            <?php
                            $fontfamily = array(
                                         '10px'=>'10px',
                                         '11px'=>'11px',
                                         '12px'=>'12px',
                                         '13px'=>'13px',
                                         '14px'=>'14px',
                                         '15px'=>'15px',
                                         '16px'=>'16px',
                                         '17px'=>'17px',
                                         '18px'=>'18px'
                            );
                            ?>
                            <select onchange="javascript: cPApply();" name="sns_ccofig_fontSize" class="cp_select">
                            <?php foreach($fontfamily as $k=>$v):?>
                                <option value="<?php echo $v; ?>"<?php echo ($var_snstheme->getParam('fontSize')==$v)?' selected="selected"':'';?>><?php echo $k; ?></option>
                            <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <!-- Body font-family -->
                    <?php if(1==0){?>
                    <div class="cp-item body-fontfamily">
                        <span>Font-family</span>
                        <div class="inner">
                        <?php 
                        $fontfamily = array(
                                     'Arial'=>'arial',
                                     'Arial Black'=>'arial-black',
                                     'Courier New'=>'courier',
                                     'Georgia'=>'georgia',
                                     'Impact'=>'impact',
                                     'Lucida Console'=>'lucida-console',
                                     'Lucida Grande'=>'lucida-grande',
                                     'Palatino'=>'palatino',
                                     'Tahoma'=>'tahoma',
                                     'Times New Roman'=>'times',
                                     'Trebuchet'=>'trebuchet',
                                     'Verdana'=>'verdana',
                                     'Segoe UI'=>'segoe ui'
                        );
                        ?>
                            <select onchange="javascript: cPApply();" name="sns_ccofig_fontFamily" class="cp_select">
                            <?php foreach($fontfamily as $k=>$v):?>
                                <option value="<?php echo $v; ?>"<?php echo ($var_snstheme->getParam('fontFamily')==$v)?' selected="selected"':'';?>><?php echo $k; ?></option>
                            <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <?php } ?>
                    <!-- Body Background color -->
                    <div class="cp-item bodyBgColor">
                        <span>Background color</span>
                        <div class="inner">
                            <input type="text" value="<?php echo $var_snstheme->getParam('bodyBgColor');?>" autocomplete="off" size="7" class="color-picker miniColors" name="sns_ccofig_bodyBgColor" maxlength="7"/>
                        </div>
                    </div>
                    <!-- Body Background image -->
                    <div class="cp-item bodyBgImage" style="margin-top:8px">
                        <span>Background image(Only applies for Boxed Layout)</span>
                        <div class="inner">
                            <input type="hidden" name="sns_ccofig_bodyBgImage" value="<?php echo $var_snstheme->getParam('bodyBgImage'); ?>"/>
                            <a href="#bd" title="pattern0 - none image" class="pattern pattern0<?php echo ($var_snstheme->getParam('bodyBgImage')=='pattern0')?' active':''?>" data-toggle="tooltip" data-original-title="pattern0 - none image">pattern0</a>
                            <a href="#bd" title="pattern1" class="pattern pattern1<?php echo ($var_snstheme->getParam('bodyBgImage')=='pattern1')?' active':''?>" data-toggle="tooltip" data-original-title="pattern1">pattern1</a>
                            <a href="#bd" title="pattern2" class="pattern pattern2<?php echo ($var_snstheme->getParam('bodyBgImage')=='pattern2')?' active':''?>" data-toggle="tooltip" data-original-title="pattern2">pattern2</a>
                            <a href="#bd" title="pattern3" class="pattern pattern3<?php echo ($var_snstheme->getParam('bodyBgImage')=='pattern3')?' active':''?>" data-toggle="tooltip" data-original-title="pattern3">pattern3</a>
                            <a href="#bd" title="pattern4" class="pattern pattern4<?php echo ($var_snstheme->getParam('bodyBgImage')=='pattern4')?' active':''?>" data-toggle="tooltip" data-original-title="pattern4">pattern4</a>
                            <a href="#bd" title="pattern5" class="pattern pattern5<?php echo ($var_snstheme->getParam('bodyBgImage')=='pattern5')?' active':''?>" data-toggle="tooltip" data-original-title="pattern5">pattern5</a>
                            <a href="#bd" title="pattern6" class="pattern pattern6<?php echo ($var_snstheme->getParam('bodyBgImage')=='pattern6')?' active':''?>" data-toggle="tooltip" data-original-title="pattern6">pattern6</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Menu -->
        <div class="accordion-group">
            <div class="accordion-heading">
                <a href="#sns_citem_2">
                Menu
                </a>
            </div>
            <div id="sns_citem_2">
                <div class="accordion-inner clearfix">
                    <!-- Styles -->
                    <div class="cp-item">
                        <span>Use sticky menu</span>
                        <div class="inner">
                            <select onchange="javascript: cPApply();" name="sns_ccofig_keepMenu" class="cp_select">
                                <option value="1"<?php echo ($var_snstheme->getParam('keepMenu')==1)?' selected="selected"':'';?>>Yes</option>
                                <option value="0"<?php echo ($var_snstheme->getParam('keepMenu')==0)?' selected="selected"':'';?>>No</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="cpanel-reset">
        <a  class="btn reset" href="#" onclick="javascript: cPReset(TMPL_COOKIE);">Reset</a>
    </div>
    <div id="sns_config_btn">
        <i class="fa fa-cog fa-spin "></i>
    </div>
</div>

    <script type="text/javascript">
    // <![CDATA[

    $sns_jq(document).ready(function($){
        /* Begin: Enabling miniColors */
        $('.bodyBgColor .color-picker').miniColors({
            change: function(hex, rgb) {
                $('body#bd').css('background-color', hex);
                createCookie(TMPL_NAME+'_'+($(this).attr('name').match(/^sns_ccofig_(.*)$/))[1], hex, 365);
            }
        });
        /* End: Enabling miniColors */
        /* Begin: Set click pattern */
        function setPattern(el, paramCookie, assign){
            $(el).click(function(){
                if(!$('#bd').hasClass('boxed-layout')){
                    alert('Only applies for Boxed Layout');
                }else{
                    oldp = $(this).parent().find('.active').html();
                    $(el).removeClass('active');
                    $(this).addClass('active');
                    newp = $(this).html();
                    if(assign.length > 0){
                        for($i=0; $i < assign.length; $i++){
                            if(oldp.length) $(assign[$i]).removeClass(oldp);
                            $(assign[$i]).addClass(newp);
                        }
                    }
                    if(paramCookie){
                        $('input[name$="sns_ccofig_'+paramCookie+'"]').attr('value', newp);
                        createCookie(TMPL_NAME+'_'+paramCookie, newp, 365);
                    }
                }
            });

        }
        setPattern('.bodyBgImage .pattern', 'bodyBgImage', Array('#bd', ''));
        /* End: Set click pattern */
    });
    // ]]>
    </script>
<?php
}
?>

<script type="text/javascript">
    $sns_jq(document).ready(function($) {
        //accordion
        $('#sns_cpanel .accordion-heading').accordion_snyderplace({
            defaultOpen: '#sns_cpanelaccordionfirst',
            cookieName: 'cpanel_accordion',
            speed: 'fast',
            animateOpen: function (elem, opts) { //replace the standard slideUp with custom function
                elem.next().slideFadeToggle(opts.speed);
            },
            animateClose: function (elem, opts) { //replace the standard slideDown with custom function
                elem.next().slideFadeToggle(opts.speed);
            }
        });
        //custom animation for open/close
        $.fn.slideFadeToggle = function(speed, easing, callback) {
            return this.animate({opacity: 'toggle', height: 'toggle'}, speed, easing, callback);
        };
    });
</script>