<?php
$options = $this->getConfigObject();
if( $options->list_products_by == 'order' ){
	$list = $this->getListByOrder();
} else {
	$list = $this->getListByCategory();
}

$uq = rand().time();
include 'scripts.phtml';
$class_res = ((int)$options->devices_wide > 0)?' wide-'.$options->devices_wide:' wide-6';
$class_res .= ((int)$options->devices_normal > 0)?' normal-'.$options->devices_normal:' normal-6';
$class_res .= ((int)$options->devices_tabletlandscape > 0)?' tabletlandscape-'.$options->devices_tabletlandscape:' tabletlandscape-6';
$class_res .= ((int)$options->devices_tabletportrait > 0)?' tabletportrait-'.$options->devices_tabletportrait:' tabletportrait-6';
$class_res .= ((int)$options->devices_mobilelandscape > 0)?' mobilelandscape-'.$options->devices_mobilelandscape:' mobilelandscape-6';
$class_res .= ((int)$options->devices_mobileportrait > 0)?' mobileportrait-'.$options->devices_mobileportrait:' mobileportrait-6';
?>
<?php if(!empty($list)){ ?>
<div id="sns_producttabs<?php echo $uq; ?>" class="sns-producttabs">
	<?php if( $options->pretext != ""){ ?>
	<div class="pre-text">
		<h2><?php echo $options->title; ?></h2>
		<?php echo $options->pretext;?>
	</div>
	<?php }?>
	<div class="sns-pdt-container">
		<!--Begin Tab Nav -->
		<?php include 'navs.phtml'; ?>
		<!-- End Tab Nav -->
		<!--Begin Tab Content -->
		<div class="sns-pdt-content<?php echo $class_res; ?>">
			<?php foreach($list as $items) :
				$child_items = isset($items->child)?$items->child:'';
				$cls = (isset($items->active) && $items->active  == 1)?' tab-content-actived is-loaded': '';
				$cls .= ($items->id == "*")?' pdt_all':' pdt_'.$items->id;
			?>
			<div class="pdt-content<?php echo $cls; ?>" >
				<div class="pdt-list products-grid<?php echo ' '.$options->effects; ?>">
				<?php
				if(!empty($child_items)){
					include 'items.phtml';
				} else {?>
					<div class="content-loading"></div>
				<?php
				} ?>
				</div>

				<?php
				$classloaded = ($options->number_per_display >= $items->count || $options->number_per_display == 0 )?' loaded':'';
				?>
				<div class="pdt-loadmore" data-href="pdt_<?php echo ($items->id == "*")?'all':$items->id; ?>"
				data-type="<?php echo $options->list_products_by; ?>"
				data-catid="<?php echo ($options->list_products_by == 'order')?"":$items->id ?>"
				data-orderby="<?php echo $items->orderid; ?>"
				data-all="<?php echo $items->count; ?>"
				data-start="<?php echo $options->number_per_display;?>"
				data-loadnum="<?php echo $options->number_per_display;?>">
					<div class="btn-loadmore<?php echo $classloaded?>"
					data-label="<?php echo ($classloaded)?$this->__('All ready'):$this->__('Load More');?>" data-label-load="<?php echo ($classloaded)?$this->__('All ready'):$this->__('Loading ...');?>" >
					<?php if( $options->show_number_loadmore ):?>
						<span class="load-number" <?php if( $items->count >$options->number_per_display ){?> data-more="<?php if( $items->count - $options->number_per_display <= $options->number_per_display ){ echo ($items->count - $options->number_per_display);}else{ echo $options->number_per_display; }?>"
						data-total="<?php  echo $items->count - $options->number_per_display;?>"<?php }?>><?php if( $items->count > $options->number_per_display ){ echo "/"; } ?></span>
					<?php endif;?>
						<span class="ico-loading"></span>
					</div>
				</div>
			</div>
			<?php
			endforeach; ?>
		</div>
	</div>
	<!--End Tab Content -->
	<?php if(!empty($options->posttext)) {  ?>
	<div class="post-text"><?php echo $options->posttext; ?></div>
	<?php } ?>
</div>
<?php } else { echo $this->__('Has no item to show!');}?>

