<!Doctype html>
<html>
<head>
    <?php echo $this->getChildHtml('head');?>
</head>

<body>
<div id="wapper">
    <div id="header" class="border-block">
        <?php echo $this->getChildHtml('header');?>
    </div>

    <div id="container">
        <div id="left" class="border-block">
            <?php echo $this->getChildHtml('left');?>
        </div>

        <div id="main" class="border-block">
            <?php echo $this->getChildHtml('content');?>
        </div>

        <div class="clear"></div>
    </div>

    <div id="footer" class="border-block">
        <?php echo $this->getChildHtml('footer');?>
    </div>
</div>
</body>

</html>