<?php
/*------------------------------------------------------------------------
 # SNS Productlist - Version 1.0
 * Copyright (C) 2013 The SNS Theme. All Rights Reserved.
 * @license - GNU/GPL, http://www.gnu.org/licenses/gpl.html
 * Author: SNS Theme
 * Websites: http://www.snstheme.com
-------------------------------------------------------------------------*/

$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$imgWidth = $this->product_image_width;
$imgHeight = $this->product_image_height;
if ($imgWidth <= 0 || $imgHeight <= 0){
	$this->product_image_disp = false;
}
?>

<div class="block sns-productlist style-default">
	<?php if ($this->title): ?>
	<div class="block-title"><?php echo $this->title; ?></div>
	<?php endif; ?>
    <div class="block-content">
    	<?php if(!$_productCollection->count()): ?>
        	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
        <?php else:?>
        <ul class="products-grid">
        <?php $i = 0;
        foreach($_productCollection as $_product):?>
        <?php
        $i++;
        $now = date("Y-m-d");
        $newsFrom= substr($_product->getData('news_from_date'),0,10);
        $newsTo=  substr($_product->getData('news_to_date'),0,10);
        $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice();
        $class = '';
        if($now>=$newsFrom && $now<=$newsTo) $class .= ' have-iconew';
        if($specialprice) $class .= ' have-icosale';
        ?>
            <li class="item col-<?php echo $this->num_columns; ?><?php if(($i-1)%$this->num_columns==0): ?> first<?php elseif($i%$this->num_columns==0): ?> last<?php endif; ?>">
                <div class="item-inner">
                	<div class="item-box">
						<?php
                        if ($now>=$newsFrom && $now<=$newsTo)
                            echo "<span class='ico-product ico-new'>new</span>";
                        if ($specialprice)
                            echo "<span class='ico-product ico-sale'>sale</span>";
                        ?>
                        <?php if ($this->product_image_disp): ?>
                        <div class="product-image">
                        	<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgWidth, $imgHeight); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                        </div>
                        <?php endif; ?>
                        <div class="item-box-hover">
                            <?php if ($this->product_cart_or_status): ?>
                            <?php if($_product->isSaleable()): ?>
                                <button title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"></button>
                            <?php else: ?>
                                <span class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></span>
                            <?php endif; ?>
                            <?php endif; ?>
                            <?php if ($this->product_addtowishlist || $this->product_addtocompare): ?>
                            <div class="actions">
                                <ul class="add-to-links">
                                    <?php if ($this->product_addtowishlist && $this->helper('wishlist')->isAllow()) : ?>
                                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                    <?php endif; ?>
                                    <?php if($this->product_addtocompare && $this->getAddToCompareUrl($_product)): ?>
                                        <li><a href="<?php echo $this->getAddToCompareUrl($_product) ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                    <?php endif; ?>
                                </ul>
                            </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php if ($this->product_title_disp): ?>
                    <!-- Product Name -->
                    <h2 class="product-name">
                    	<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                        <?php
                            if ( $this->product_title_max_length > 0){
                                $_productNameTruncated = Mage::helper('core/string')->truncate($_productNameStripped, $this->product_title_max_length);
                            }
                        ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo isset($_productNameTruncated) ? $_productNameTruncated : $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
                    </h2>
                    <?php endif; ?>
                    <!-- More Info: price, rating -->
                    <div class="more-info clearfix">
                        <?php if ($this->product_price_disp): ?>
                        <?php echo $this->getPriceHtml($_product, false, rand().time()) ?>
                        <?php endif; ?>
                        <?php
                        if( $this->product_rating_summary ){
                            Mage::getModel('review/review')->getEntitySummary($_product, Mage::app()->getStore()->getId());
                            if ( $_product->getRatingSummary() ){
                                echo $this->getReviewsSummaryHtml($_product,'short');
                            }
                        } ?>
                    </div>
                    <?php if ($this->product_description_disp): ?>
                    <!-- Description -->
                    <div class="item-description">
                        <?php
                            $product_description_src = in_array($this->product_description_src, array('short_description', 'description')) ? $this->product_description_src : 'short_description';
                            $product_description = $_helper->productAttribute($_product, $_product->$product_description_src, $product_description_src);
                            if ( $this->product_description_strip_tags ){
                                $allow_tags = $this->product_description_keep_tags ? $this->product_description_keep_tags : null;
                                $product_description = $this->stripTags( $product_description,  $allow_tags, true);
                            }
                            if ( $this->product_description_max_length > 0){
                                $product_description = Mage::helper('core/string')->truncate($product_description, (int)$this->product_description_max_length);
                            }
                            echo $product_description;
                        ?>
                    </div>
                    <?php endif; ?>
            	</div>
            </li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>
	</div>
</div>
