<title><?php echo $this->getTitlePage() ? $this->getTitlePage() . ' - ' : ''; ?>Grocery</title>
<!-- Latest compiled and minified CSS -->
<!--<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">-->

<!-- Optional theme -->
<!--<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">-->

<!-- Latest compiled and minified JavaScript -->
<!--<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>-->

<link rel="stylesheet"
      href="<?php echo $this->getSkinDes();?>bootstrap-3.2.0/css/bootstrap.min.css"/>

<link rel="stylesheet"
      href="<?php echo $this->getSkinDes();?>bootstrap-3.2.0/css/bootstrap-theme.min.css"/>

<link rel="stylesheet"
      href="<?php echo $this->getSkinDes();?>css/styles.css"/>

<?php
    echo $this->getChildHtml('head_1col');
    echo $this->getChildHtml('head_3col');
?>

<script
    src="<?php echo $this->getSkinDes();?>js/jquery-1.11.1.min.js">
</script>

<script
    src="<?php echo $this->getSkinDes();?>bootstrap-3.2.0/js/bootstrap.min.js">
</script>
<!--
<script type="text/javascript" src="<?php /*echo Mage::getBaseUrl('skin'); */?>frontend/grocery/default/milonic/js/milonic_src.js"></script>
<noscript><a href="http://www.milonic.com/">JavaScript DHTML Menu Powered by Milonic</a></noscript>
<script type="text/javascript" src="<?php /*echo Mage::getBaseUrl('skin'); */?>frontend/grocery/default/milonic/js/mmenudom.js"></script>
<script type="text/javascript" src="<?php /*echo Mage::getBaseUrl('skin'); */?>frontend/grocery/default/milonic/js/menu_data.js"></script>-->